# 存储提示模版

# 获取SET\GET函数信息
SYSTEM_SET_GET = "You are a firmware reverse engineering specialist tasked with analyzing firmware binaries to identify functions that utilize key-value pair mechanisms for persistent configuration storage or retrieval (e.g., apmib_set/apmib_get, nvram_safe_set/nvram_safe_get). Your task is divided into two distinct phases:\
    1. Function Pair Identification Based on Naming Semantics: Given a list of function names, infer all potential key-value related function pairs purely based on naming conventions and common patterns observed in firmware development. These typically follow set/get pairings for storing and retrieving values. Output the identified function pairs strictly in the format: [(set_1, get_1), (set_2, get_2), ...], for example: [(nvram_safe_set, nvram_safe_get), (apmib_set, apmib_get)], If no relevant pairs are found, return None. Note: You must output only the final answer in the specified format, with no additional explanation or commentary.\
    2. Argument Role Inference from Decompiled Usage Patterns: Given actual usage examples of the candidate function pairs within decompiled binary code, refine the results by eliminating function pairs that are not genuinely related to key-value storage. For each validated function pair, identify the argument positions (using zero-based indexing) corresponding to: the key in the set function, the value in the set function, the key in the get function, and the value in the get function. If any of these positions are not applicable or cannot be determined, use None for that field. Output the results strictly in the format: [(set_1, get_1, set_key_pos, get_key_pos, set_value_pos, get_value_pos), ...]. Note: Again, you must output only the answer in the specified format with no extraneous information."
    
SYSTEM_SET_GET_OUTPUT_PHASE_ONE = "Please strictly output in the format [(set_1, get_1), (set_2, get_2), ...] or None in the first phase."

SYSTEM_SET_GET_OUTPUT_PHASE_TWO = "Please strictly output in the format [(set_1, get_1, set_key_pos, get_key_pos, set_value_pos, get_value_pos), ...] or None in the second phase."

DOUBLE_CHECK = "Please double check and answer again."

def get_user_set_get_en_prompt_phase_one(name_list):
    return f"Input for the first phase: {name_list}."

def get_user_set_get_en_prompt_phase_two(code_list):
    return f"Input for the second phase: {code_list}."

def double_check_phase_two(code_list):
    return f"Please double check and answer again with new input: {code_list}."

# 进行敏感路径的过滤
SYSTM_LLM_PATH_CHECK = "You are an expert program analyst specializing in binary vulnerability detection using taint analysis. Your task is to assist in analyzing C code generated by decompilation, focusing on tracking the propagation of tainted data from sources (such as external input functions) to sensitive sinks (such as memory operations or system calls). For each conversation, you will receive one or more code snippets and analysis instructions. \n \
    Your objectives are:\n \
        1. Taint Flow Analysis: Identify and trace the flow of tainted data from the specified source and parameter, considering data dependencies, data aliasing, and any transformations along the way.\n \
        2. Vulnerability Assessment: Based on the results of the taint flow analysis, determine whether the code contains any vulnerabilities related to tainted data reaching sensitive sinks.\n \
        3. Vulnerability Classification: If a vulnerability is found, classify it according to the Common Weakness Enumeration (CWE) standard, and briefly explain the reason.\n \
    Output Requirements:\n \
        - For each analysis step, provide a clear, step-by-step summary of the taint flow and data dependencies. \n \
        - For the final vulnerability assessment, your answer must begin with either “Yes” or “No” to indicate whether an exploitable vulnerability exists. If “Yes”, specify the CWE type and provide a concise explanation.\n \
        - Use formal, precise language suitable for professional program analysis. \n \
        - Do not make assumptions beyond the provided code and instructions. If the information is insufficient to reach a conclusion, explicitly state the uncertainty.\n \
    You will receive further analysis instructions and code snippets in subsequent messages." 
    
def get_start_prompt(function_name, code_snippet):
    start_prompt = f"As a program analyst, you are provided with the following snippet of C code generated by decompilation. Please use the first {function_name} as the taint source to extract the taint data flow. Pay close attention to data dependencies, aliasing, and tainted data operations during your analysis. Present the taint flow step by step. \
        For each step: Clearly indicate how the taint propagates, is sanitized, or is aliased.\n \
        At the end of your analysis, do not yet judge the presence of vulnerabilities. Simply provide a structured summary of the taint flow and data propagation within the given code snippet.\n \
        {code_snippet}"
    return start_prompt

def get_middle_prompt(code_snippet):
    middle_prompt = f"Continue the taint analysis for the following C code snippet, building on the previous taint flow analysis results. Focus on tracking the propagation, sanitization, and aliasing of tainted data, considering any new taint sources identified in this function (if applicable). Clearly indicate each step of the taint flow, including how tainted data moves, changes, or is sanitized. \
        For each step: Explicitly describe how taint is propagated, aliased, or sanitized in this function, and note any updates to the taint label(s).\n \
        At this stage, do not assess whether a vulnerability exists. Only provide a structured, step-by-step summary of the taint flow within this code snippet, taking into account the taint analysis results from previous steps.\n \
        {code_snippet}"
    return middle_prompt

def get_end_prompt(function_name):
    end_prompt = f"Based on the above taint analysis results, using the last {function_name} in the final snippet as sink, determine whether the code snippet contains any exploitable vulnerabilities caused by tainted data reaching sensitive sinks. \n \
        Only base your judgment on the information present in the provided code. Do not make assumptions or speculate about possible vulnerabilities beyond what is explicitly shown. Only confirm a vulnerability if it definitely exists in the code snippet; do not output results for potential or hypothetical cases.\n \
        Your answer must begin with either “Yes” or “No” to indicate whether an exploitable vulnerability exists. \n \
            - If “Yes”, specify the CWE type (according to the Common Weakness Enumeration) and provide a concise explanation for the vulnerability.\n \
            - If “No”, briefly explain why no exploitable vulnerability is present.\n \
        Your explanation should be formal, precise, and suitable for professional program analysis."
    return end_prompt

SYSTM_LLM_PATH_OUTPUT = "Your answer must begin with either “Yes” or “No” to indicate whether an exploitable vulnerability exists."